### ISSUE TITLE
Fail to run MAKEFILE

### ISSUE THREAD

**Issue by sanggod** [gadam2018/RPi3-DALI#2]
make -C /lib/modules/4.19.97-v7+/build M=/home/pi/Dali/RPi3-DALI/RPi3-DALI-master modules
make[1]: *** /lib/modules/4.19.97-v7+/build: No such file or directory.  Stop.

**Comment by gadam2018** [comment]
Perhaps the lib modules are not installed or the version is different.

**Comment by sanggod** [comment]
thanks for your instant reply. 
May I have your advice on how to install the lib modules?

**Comment by gadam2018** [comment]
Well as I said there is some time passed and I can't remember a few things. I have to see where I have placed the files with the detailed procedures. Give me some time to have a look. In addition, please have a look at a relevant publication https://www.mdpi.com/2079-9292/8/9/1021 in case you find some useful information.

**Comment by sanggod** [comment]
I have succesfully run the MAKEFILE after installing the kernel header in Pi3.
Thanks. But still , facing the error Value of fd is: -1 Cannot open device

**Comment by gadam2018** [comment]
Dear fellow,
I am glad that you manage to run the Makefile.
Now about the failure to open the device and the returned error value, although it seems something simple to tackle, I can't remember what we did to succeed. Our team is now engaged with other development platforms and this setup is widthdrawn in order to go ahead and check it.
Therefore I am not sure if I could find out any solution, but as I said I will try. In this case I will inform you. Meanwhile, have a look/search at the web. Perhaps similar problems were encountered, which we followed too to solve it.
Best regards.

**Comment by sanggod** [comment]
Thanks for your comment. 
I think the failure to open the device is caused by failing to find the kernel module driver "#define DALI_drv "/dev/RPi_DALI_drv"	

do you know is there any hints that I could makesure "/dev/RPi_DALI_drv" is installed/loaded correctly? I am not able to find RPi_DALI_drv in /dev/ folder under root.

Hope these can bring you some memory :)

**Comment by gadam2018** [comment]
Well if “sudo insmod RPi_DALI_drv.ko” is successful (with no error messages) it should have been loaded correctly.
I can’t remember which one works, here follow a few thoughts for checking if it is loaded correctly:
lsmod
cat /proc/modules 
cat /proc/devices
ls -l  /dev/RPi_DALI_drv 
Perhaps the problem has to do with the permissions (probably only root has rw permissions).
Check your permissions (perhaps you have to use sudo or change permissions with chmod).
Sorry, but I can’t remember further at the moment.

**Comment by sanggod** [comment]
Cool! we are now very close to solve the problem.
The make -f MAKEFILE cannot help to put RPi_DALI_drv.ko to lsmod
lsmod cannot find RPi_DALI_drv.ko
what we need is to get RPI_DALI_drv.ko into lsmod
if makefile didnt work, would it be other workaround?

**Comment by sanggod** [comment]
insmod succesfully
lsmod , RPi_DALI_drv.ko is running
pi@raspberrypi:~ $ ls -l /dev/RPi_DALI_drv
crw------- 1 root root 240, 0 Apr  23 23:07 /dev/RPi_DALI_drv

but still, value of fd is -1, cannot open device.. V_V

**Comment by gadam2018** [comment]
You are doing progress. That is pleasant.
As I said, at the moment I am not in position to provide any further help (the platofrm setup is withdrawn -which makes it more difficult for me to find out what is going on-, and I am also engaged on other intensive research work having strict deadlines), but I will try to look for it (in the meantime, in anycase, as I said previously, do a web search with this error message, you may get a quicker answer).

**Comment by sanggod** [comment]
Understand :) Thanks for your great effort.

**Comment by sanggod** [comment]
Finally, I can run the program!
however, it still cannot communicate with the DALI device.
May I know, which protocol that your driver is using? i2c? UART? or Serial?
